### ISSUE TITLE
Reporting functionality in v3

### ISSUE THREAD

**Issue by michal-kocarek** [bencompton/jest-cucumber#102]
Hello,

first of all, thanks for this great project, it is pleasure to use it.

I recently found out, there is version 3, which is great, but the "reporting" scripts is missing from the published NPM package. I noticed it was removed also from 2.0.12. 

Can I ask you about the intention? We are relying on them to produce JSON for further reporting, but now we cannot. What would you recommend us and/or is there some help that you might need with this functionality?

Thank you.

**Comment by michal-kocarek** [comment]
Actually, I am sorry... I got confused that the contents of v3 NPM package do not match with what is on github in master, as version v3.

What is the problem that we are facing, is that your package.json doesn't specify **dependency on cucumber ^5.1.0** anymore, but even if I added the cucumber dependency back, it wasn't working.

This is extract of our jest.config:
```
module.exports = {
  reporters: [
    [
      require.resolve('jest-cucumber/dist/src/reporter'),
      {
        formatter: 'json',
        path: './coverage/sit-test-results.json',
      },
    ]
};
```

Could you recommend me some way to get to these lovely jsons again? Thank you...

**Comment by bencompton** [comment]
Reporting unfortunately was broken after 2.0.12 due to some breaking changes in the Cucumber library, but there are plans to fix it. #27 is already being used for this discussion, so I'm going to close this one.
