### ISSUE TITLE
Scenario outline with placeholder in title won't work

### ISSUE THREAD

**Issue by andreyivlev-sidekick** [bencompton/jest-cucumber#106]
Consider the following scenario (my case, test for webpage with a sidebar):

```cucumber
Feature: Sidebar

  Background:
    Given I've already authed and onboarded

  Scenario Outline: Should have tooltip on <ButtonLabel> button
    When Hover element labeled <ButtonLabel>
    Then Tooltip is visible
    Then Tooltip contains text "<ExpectedTooltip>"

    Examples:
      | ButtonLabel  | ExpectedTooltip         |
      | Settings     | Show Settings           |
      | Home         | Home                    |
      | Sessions     | Manage Sessions         |
      | Help         | Help                    |
      | Notes        | Notes                   |
      | Mute         | sound and notifications |
```

It works fine if `Scenario Outline` has no placeholders in title but it fails with following error when `Scenario Outline` title has placeholders

```
Sidebar encountered a declaration exception

No scenarios found in feature file that match scenario title "Should have tooltip on Settings button."

Feature file has a scenario titled "Should have tooltip on <ButtonLabel> button", but no match
found in step definitions. Try adding the following code:

(sample test code)
```

I really need placeholders to work correctly in titles to make jest console output and snapshot names more human friendly. Otherwise I see a lot of same test results like this:

![image](https://user-images.githubusercontent.com/69784060/96875894-6ce13500-1480-11eb-8caa-1cb25913cfdd.png)

And it's impossible to tell which case failed because jest on CI/CD server runs everything in a parallel and order is not guaranteed.

**Comment by mentierd** [comment]
@andreyivlev-sidekick you should check out [cucumber-jest](https://github.com/mentierd/cucumber-jest#output), it doesn't have this problem. It is a jest transformer that allows you to use the cucumber api with jest.
