### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by stevensnoeijen** [bencompton/jest-cucumber#107]
Hi, I'm trying to use https://www.npmjs.com/package/jest-cucumber-fusion with another language (than english).
So jest-cucumber-fustion uses jest-cucumber, but seems it doesn't support languages atm. 
Apparently, jest-cucumber works with languages (not officially supported I think?). But jest-cucumber-fusion doesn't because it uses the `keyword` returned in the `loadFeature`, `scenarios.steps[0].keyword` (and `scenarioOutlines`) and with other languages it returns the keyword in that language.
To fix this I would like to add a translation in jest-cucumber to correctly return the `keyword`, with: https://github.com/cucumber/gherkin-javascript/blob/master/src/gherkin-languages.json

Any thoughts on this?
Otherwise I'll make a pr for this :)

**Comment by bencompton** [comment]
Closing since the PRs concerning this feature were merged.
