### ISSUE TITLE
Is `jest` really a depedency?

### ISSUE THREAD

**Issue by LeonardDrs** [bencompton/jest-cucumber#108]
Hi!

I've dig in this repo and I can't find any import from jest in the codebase. I feel like `jest` should be a devDependency/peerDependency over a dependency.

Also these :point_down: should also be devDeps.
```
    "@types/glob": "^7.1.3",
    "@types/jest": "^26.0.7",
    "@types/node": "^11.9.4",
```

Am I mistaken?

**Comment by filipkastovsky** [comment]
It depends, devdeps will be omitted when installing a package, that would mean that if `jest-cucumber` exports anything that requires (or builds upon) these types, they would be lost and require you to install them additionally.

As for jest, it is not explicitly imported per se, rather the runner injects jest as a global object when running tests. While specifying jest as a peer dependency would work, the only benefit to that I see is if you were to run your own `jest` tests in the same project alongside `jest-cucumber` while using a very different version of `jest`.

**Comment by LeonardDrs** [comment]
>It depends, devdeps will be omitted when installing a package, that would mean that if jest-cucumber exports anything that requires (or builds upon) these types, they would be lost and require you to install them additionally.

Yes indeed, but I did not see any public usage (export) of theses types. 

>As for jest, it is not explicitly imported per se, rather the runner injects jest as a global object when running tests. While specifying jest as a peer dependency would work, the only benefit to that I see is if you were to run your own jest tests in the same project alongside jest-cucumber while using a very different version of jest.

Rather than would work, it's actually the [best practice](https://nodejs.org/es/blog/npm/peer-dependencies/).
And I feel like this only benefit is actually pretty common. The host often needs to have their very own jest tests without having to rely on the specific version of `jest-cucumber`. They would probably have `jest` installed before `jest-cucumber` and this will lead to two different `jest` version.
What I'm proposing is a `peerDependency` for `jest` with major jest versions supported to avoid this - what I feel like - common issue.

What are the counterpoints?

**Comment by bencompton** [comment]
Agreed that Jest should be a peer dependency, and have updated it on master (also a dev dependency because the examples require it to run). This change will be in the upcoming v4 of this package.
