### ISSUE TITLE
The autoBindSteps could not see the Scenario Outline with <variables>

### ISSUE THREAD

**Issue by dizzyn** [bencompton/jest-cucumber#110]
If I use such am outline scenarios:

![image](https://user-images.githubusercontent.com/2071816/100868916-912b2b00-349c-11eb-921f-452ec94f4fd8.png)

I can reach them by regular step definitions:
````
 test('Exporting all localizations (<Localization_name> - <Export_type> translation strings)', async ({given, and}) => {
        given('User is on Localization page', userIsOnLocalizationPage);

        and('User has all localizations present', async () => {
````
BUT I can not reach them by the `autoBindSteps(` this is the error report:
![image](https://user-images.githubusercontent.com/2071816/100869712-b2404b80-349d-11eb-9197-f3928e706cb5.png)

Thank You

**Comment by mentierd** [comment]
@dizzyn you should check out [cucumber-jest](https://github.com/mentierd/cucumber-jest). It a jest transformer that allows you to use the cucumber api with jest. It provides all the benefits of executing cucumber tests with jest, without a custom api.

**Comment by cabillin** [comment]
Thanks for this awesome library! I am experiencing the same issue. Is there an estimated timeline for a fix?
