### ISSUE TITLE
Clarification on loadFeature error flag settings

### ISSUE THREAD

**Issue by ablamunits** [bencompton/jest-cucumber#111]
The[ configuration options documentations ](https://github.com/bencompton/jest-cucumber/blob/master/docs/AdditionalConfiguration.md#configuration-options) suggest that the following flags can be set to configure the conditions under which `jest-cucumber` will throw an error:

```
import { defineFeature, loadFeature } from 'jest-cucumber';

const feature = loadFeature('./features/RocketLaunching.feature', {
  errors: {
    missingScenarioInStepDefinitions: true, // Error when a scenario is in the feature file, but not in the step definition
    missingStepInStepDefinitions: true, // Error when a step is in the feature file, but not in the step definitions
    missingScenarioInFeature: true, // Error when a scenario is in the step definitions, but not in the feature
    missingStepInFeature: true, // Error when a step is in the step definitions, but not in the feature
  }
});
```

However I did notice that some of these flags are either not respected in the codebase at all, or are respected inconsistently. Here are some examples I noticed which I found a bit confusing:

- `missingStepInFeature`: The docs suggest this will error when a feature file is missing a step that exists in my step definitions. However, this flag is only considered when checking for [multiple matching scenarios](https://github.com/bencompton/jest-cucumber/blob/02b30c4cd52142a75af3eba8d6e911b80bf285f8/src/validation/scenario-validation.ts#L28).
- `missingStepInStepDefinitions`: This flag does not seem to be used anywhere in the code.

My personal use case here is that I am expecting that setting `missingStepInFeature: false` would allow me to create scenarios without any steps in feature files. I would expect `jest-cucumber` to respect that when I switch the above flag off, and only error on missing/mismatching _scenario titles_.

Could you please clarify what these flags were designed to control? I am happy to create a PR and help here.

**Comment by bencompton** [comment]
Thank you for providing this detailed description in this issue. You are correct that the error flags were implemented inconsistently. I just added feature files and integration tests for this validation and code generation functionality, and the process of writing [scenarios to describe how they work](https://github.com/bencompton/jest-cucumber/blob/6373794236fdb8e686f0f38d8208c119457311b9/specs/features/validation-and-code-generation.feature) and [test them](https://github.com/bencompton/jest-cucumber/blob/6373794236fdb8e686f0f38d8208c119457311b9/specs/step-definitions/validation-and-code-generation.steps.ts) made me realize that not only were they not working as expected like you reported, but that they needed to reworked to be more clear. I guess writing Gherkin acceptance tests is a valuable practice after all--who would have thought. ;)

Anyhow, the next upcoming version will have `scenariosMustMatchFeatureFile`, `stepsMustMatchFeatureFile`, and `allowScenariosNotInFeatureFile`. Your use case would be covered by enabling `scenariosMustMatchFeatureFile` and disabling `stepsMustMatchFeatureFile`, which would validate only the scenarios and ignore the steps. I also added a [passing scenario](https://github.com/bencompton/jest-cucumber/blob/6373794236fdb8e686f0f38d8208c119457311b9/specs/features/validation-and-code-generation.feature#L88) specifically for this use case.

Hopefully having a full set of integration tests covering the entirety of Jest Cucumber will prevent issues like this in the future.
