### ISSUE TITLE
Your test suite must contain at least one test at onResult

### ISSUE THREAD

**Issue by mkhslaa** [bencompton/jest-cucumber#112]
shared.steps.ts
----------------
import { HttpClient } from '../helper/http.client'
import { IHttpClientRequestParameters } from '../helper/http.client.interfaces'
import { Login } from '../helper/Login'

let httpClient: HttpClient
let getParameters: IHttpClientRequestParameters<any>
type Payload = {
  user: {
    email: string
    password: string
  }
}
let payload: Payload = {
  user: {
    email: 'manjeet@test.com',
    password: 'Garden18',
  },
}

//To share the steps among multiple feature files
export const givenIhaveLogin = (given: any, login: Login) => {
  given(/^I login "(.*)"$/, (url: string) => {
    console.log(`I login with url - ${url}`)
    httpClient = new HttpClient()
    getParameters = {
      url: url,
      requiresToken: false,
      token: 'my-token',
      payload: payload,
    }
    return httpClient.post<any, Payload>(getParameters).then((res) => {
      console.log('shared login res', res.data.user.token)
      login.setToken(res.data.user.token)
    })
  })
}

-----------------

post.artlcles.steps.ts
----------------------
import { loadFeature, defineFeature } from 'jest-cucumber'
import { AxiosResponse } from 'axios'
import { HttpClient } from '../helper/http.client'
import { IHttpClientRequestParameters } from '../helper/http.client.interfaces'
import * as dotenv from 'dotenv'
import * as path from 'path'
import { givenIhaveLogin } from '../step-definitions/shared.steps'
import { Login } from '../helper/login'

let envfile = '.env'
if (process.env.NODE_ENV) {
  envfile += '.' + process.env.NODE_ENV
}

const result = dotenv.config({
  path: path.resolve(`src/env/${envfile}`),
})
if (result.error) {
  throw result.error
}

const feature = loadFeature('../features/post.articles.feature', {
  loadRelativePath: true,
})
defineFeature(feature, (test) => {
  let res: any
  let httpClient: HttpClient
  let getParameters: IHttpClientRequestParameters<any>
  let login = new Login()
  beforeEach(() => {})

  beforeAll(async () => {
    jest.setTimeout(10000)
  })
  type LoginPayload = {
    user: {
      email: string
      password: string
    }
  }
  let loginPayload: LoginPayload = {
    user: {
      email: 'manjeet@test.com',
      password: 'Garden18',
    },
  }

  type Payload = {
    article: {
      title: string
      description: string
      body: string
      tagList: string[]
    }
  }
  let payload: Payload = {
    article: {
      title: 'new year 2021 by MK',
      description: 'new year 2021 by MK',
      body: 'new year 2021 by MK',
      tagList: ['newyear21'],
    },
  }

  test('(+) Post articles', async ({ given, and, when, then }) => {
    givenIhaveLogin(given, login)

    and(/^I prepare the POST request for the endpoint "(.*)"$/, async (url) => {
      console.log('login get token outside', login.getToken())
      httpClient = new HttpClient()
      getParameters = {
        url: url,
        requiresToken: true,
        token: login.getToken(),
        payload: payload,
      }
    })

    when(/^I submit the POST request$/, async () => {
      res = await httpClient.post<any, Payload>(getParameters)
      // console.info('res is ', res)
    })

    then(/^I see the OK response with status code (\d+)$/, async (status) => {
      console.log('then step is executed', status)
      expect(res.status).toBe(200)
      expect(res.statusText).toEqual('OK')
    })
  })
})

----------------------

post.artcles.feature
---------------------
Feature: Post articles api tests

  Scenario:(+) Post articles
    Given I login "https://conduit.productionready.io/api/users/login"
    And I prepare the POST request for the endpoint "https://conduit.productionready.io/api/articles"
    When I submit the POST request
    Then I see the OK response with status code 200
---------------------------

Upon running test (npm run test), below error
---------------------------------------------------

 FAIL  src/step-definitions/shared.steps.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
          at Array.map (<anonymous>)
------------------------------

package.json
--------------
{
  "name": "manjeet-jest-teting-http-apis",
  "version": "1.0.0",
  "description": "Integration tests in jest",
  "main": "index.js",
  "scripts": {
    "clean:dist": "rimraf dist",
    "build": "tsc",
    "test": "npm run build & jest --color",
    "integration": "jest ./integration-tests/",
    "features": "jest ./cucumber/step-definitions",
    "test-watch": "test --watch",
    "report": "node reports/cucumber-report-config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/dotenv": "^8.2.0",
    "@types/dotenv-flow": "^3.1.0",
    "@types/jest": "24.9.0",
    "@types/node": "^14.14.16",
    "dotenv": "^8.2.0",
    "dotenv-flow": "^3.2.0",
    "gherkin": "^9.0.0",
    "jest": "26.6.3",
    "jest-cucumber": "2.0.12",
    "rimraf": "^3.0.2",
    "source-map-support": "^0.5.19",
    "ts-jest": "^26.4.4",
    "ts-node": "^9.1.1",
    "tslint": "^6.1.3",
    "typescript": "^4.1.3",
    "cucumber-html-reporter": "5.1.0"
  },
  "jestJsonReporter": {
    "outputFile": "reports/test-report.json"
  },
  "dependencies": {}
}

-----------------------------

please help.
Kind Regards - Manjeet

**Comment by Jon-Biz** [comment]
I'm experiencing this too, for several weeks. I have:

* Switched to node LTS (v14.7.6)
* Created a fresh repo with nothing but jest and jest-cucumber installed
* Installed jest @26.1.0
* Installed jest's dependencies @26.1.0 (@jest/core, jest-cli)

I'm on OSX, v10.14.6.

**Comment by Jon-Biz** [comment]
Still unable to get jest-cucumber to work, even with fresh installs. Rolling back jest-cucumber and jest to previous versions does not resolve the issue, suggesting breaking changes in dependencies? 

```
 FAIL  ./test.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:173:18)
```
