### ISSUE TITLE
How to store token in global variable and share across various steps

### ISSUE THREAD

**Issue by mkhslaa** [bencompton/jest-cucumber#113]
This may not be an issue but I would like to know how to store a token once and then use this globally in other steps in the various API calls.

Example: call a login api. Retrieve token from the response. Store somewhere
Use the token in creating articles ( another post api)

**Comment by mkhslaa** [comment]
I have managed to do that. I have created a class. In the class, I have steps. For example, "Given I login". In the step I do POST http request for login. In the response, there is a token. Retrieve token and store. Later on use getter to get this

I instantiate this class in "defineFeature". And step from class within the test.

I would welcome if there is any better way to do this.

**Comment by Anthony-J-Garot** [comment]
For jest-cucumber steps, I created a localStorageMock similar to https://stackoverflow.com/a/59477253/4171820.
