### ISSUE TITLE
Expressions not matching the RegEx

### ISSUE THREAD

**Issue by pdashford** [bencompton/jest-cucumber#115]
Hi, I want to pass in multiple string into my when function but it doe's not match the regex, yet when I put the regex in online it matches;

``` When I add the pen product with a quantity of 100 to the project purchase order```

So on this `pen` will be the product i also want to pass in more variations ```When I add the `pen` to the `basket` with a quantity of `100`

I tried using  I add the `(.*)` to the `(.*)` with a quantity of (\d+)

But always fails and tries to imply that the changes are not there 

```xpected step #2 in scenario "Creating a project purchase order" to match "I add the pen product with a quantity of 100 to the project purchase order". Try adding the following code:

    when(/^I add the pen product with a quantity of (\d+) to the project purchase order$/, (arg0) => {

    });```


```export async function whenIAddAProductToAProjectPurchaseOrder(when) {
    when(
        /^I add the \s*(\S+) product with a quantity of (\d+) to the project purchase order$/,
        async (product, quantity) => {
            expect(product).toEqual('PP')
        }
    )
}```

Thanks

**Comment by DiegoFBenavides** [comment]
Hi! same problem here. Any solution?

**Comment by bencompton** [comment]
I tried to reproduce, with the feature text and step definitions below, and the test passed as expected. Not sure if I'm misunderstanding the issue. You also had ```When I add the pen to the `basket` with a quantity of `100` above, which I wouldn't expect to be matched by the regex below because it has backticks and also says some extra text.

Can someone provide a feature file and step definition that reproduces what you're seeing?

```
Scenario: Adding to purchase order
    When I add the PP product with a quantity of 2 to the project purchase order
```

```
test('Adding to purchase order', ({ when }) => {
    when(
        /^I add the \s*(\S+) product with a quantity of (\d+) to the project purchase order$/,
        async (product, quantity) => {
            expect(product).toEqual('PP');
            expect(quantity).toBe('2');
        });
});
```
