### ISSUE TITLE
beforeAll is execute after tests begins

### ISSUE THREAD

**Issue by DanielHGimenez** [bencompton/jest-cucumber#124]
I'm using jest-cucumber to run my tests. In definition of feature, I call `setup()` method that will set `beforeAll`, `beforeEach` and `afterEach` callbacks. The `beforeAll` callback will execute `startInTestMode` method, which will get up the server application that will be used in tests. When I run the tests, things that should be defined in `startInTestMode` are not defined yet. When I debug de code, the `beforeAll` is executed after tests begins. 

```typescript
const feature = loadFeature(__dirname + '/../features/create_redirect_url.feature')

defineFeature(feature, test => {

    setup()

    test('Successfully create a url for new user', ({ given, when, then }) => {

        given('user is logged in', userIsLoggedIn())

        [...]
```

```typescript
export default function setup() {
    beforeAll(async () => {
        await startInTestMode()    })
    beforeEach(async () => {
        await Cart.deleteMany({})
        nock.cleanAll()
    })
    afterAll(async () => {
        await MongoDbMock.stopDbMock()
    })
}

export async function startInTestMode() {
    DotenvConfig.configure()
    InversifyConfig.configure()
    ExpressConfig.configure()
    ApplicationConfig.configure()

    await MongoDbMock.initDbMock()
}
```

**Comment by bencompton** [comment]
I'm wondering if you meant `given('user is logged in', () => userIsLoggedIn())` instead. I'm not sure what `userIsLoggedIn` is doing, but if that's actually performing logic that you'd expect to run when your tests execute, the way you have it now would run that logic immediately before your tests even start.

**Comment by DanielHGimenez** [comment]
userIsLoggedIn is a method factory.

```typescript
export function userIsLoggedIn() {
    return () => {
        nock(process.env.AUTH_URL!)
            .get('/auth')
            .reply(200, {
                id: 1
            })
    }
}
```
}

**Comment by DanielHGimenez** [comment]
The problem is not in that function. In another function, I get data from `process.env.KEY`, which should be initialized when `DotenvConfig.configure()` is called. But the tests start, the Scenario begins, and `beforeAll` is not executed yet

**Comment by DanielHGimenez** [comment]
Sorry, I made a mistake. The problem is not in jest-cucumber
