### ISSUE TITLE
Allure2 integration not working - Any example on how to do it?

### ISSUE THREAD

**Issue by xescuder** [bencompton/jest-cucumber#126]
I am trying to use jest-cucumber with allure2, but steps are not generated, for example, so I've tried to use a reporter like this:

```
var CucumberJSAllureFormatter = require("allure-cucumberjs").CucumberJSAllureFormatter;
var AllureRuntime = require("allure-cucumberjs").AllureRuntime;

function Reporter(options) {
  return new CucumberJSAllureFormatter(
    options,
    new AllureRuntime({ resultsDir: "./allure-results" }),
    {}
  );
}

Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype);
Reporter.prototype.constructor = Reporter;

exports.default = Reporter;

```

But next error arises:

TypeError: An error occurred while adding the reporter at path "/Users/escuderx/Projects/lni/lni-e2e-tests/support/allure/reporter.js".Reporter is not a constructor

**Comment by mandeep1987** [comment]
Any luck on the reporting? 
We need to get some good reporting for the scenarios executed. Currently it doesnt support any scenario based reporting.

**Comment by xescuder** [comment]
Not luck. I've removed Jest and I am using only Cucumber...
