### ISSUE TITLE
Option to generate scenarios with `it` alias instead of `test`

### ISSUE THREAD

**Issue by cscheffauer** [bencompton/jest-cucumber#130]
Hi,

right now when code is generated, the tests always start with Jests `test` keyword. Would it be possible to add an option to use the `it` alias instead? see [here](https://jestjs.io/docs/api#testname-fn-timeout)

I think the pieces of code which should be touched then are here:
https://github.com/bencompton/jest-cucumber/blob/1a9ef75f5602d5b18dd4b33d08130e878799da59/src/code-generation/scenario-generation.ts#L7

**Comment by bencompton** [comment]
Actually, this is already possible by naming the `test` function argument whatever you like. For example, both of these are equivalent:

```
defineFeature(feature, (test) => {
    test('Entering a correct password', ({ given, when, then }) => {
...
...
```

```
defineFeature(feature, (scenario) => {
    scenario('Entering a correct password', ({ given, when, then }) => {
...
...
```

The main downside is that certain tools may not work, like the Jest VSCode plug-in might not recognize a `scenario` in the same it recognizes a `test`.
