### ISSUE TITLE
Support Jest 27

### ISSUE THREAD

**Issue by j8kin** [bencompton/jest-cucumber#131]
Jest 27 has some breaking changes against Jest 26 and earlier.
for example Jest 27 is incompatible with jest-cli 26:
 "..../node-modules/jest-environment-jsdom/build/index.js" does not export "getVmContext" method, which is mandatory from Jest 27. This method is replacement for "runScript".

At the same time they have backward compatibility.
So it would be nice to support Jest 27

**Comment by Prior99** [comment]
We also need support for jest 27.

**Comment by j8kin** [comment]
@Prior99 actually I've already open PR to support Jest 27: https://github.com/bencompton/jest-cucumber/pull/132
but not able to connect with this issue.
