### ISSUE TITLE
Tag filtering globally with config?

### ISSUE THREAD

**Issue by siraajahmed** [bencompton/jest-cucumber#137]
Hi 

We have 100+ of these tests and we want to ignore a certain tag from all them without having to update each step file individually.

Is there a way to do this through configuration?

Thanks

**Comment by madhusudhan-patha** [comment]
There are some steps defined here to configure tags. But for me it is triggering all feature files even after configuring the tags as described here.

https://github.com/bencompton/jest-cucumber/blob/master/docs/AdditionalConfiguration.md#global-configuration
