### ISSUE TITLE
scenarioNameTemplate option is not working with scenario outline

### ISSUE THREAD

**Issue by dartyuhov** [bencompton/jest-cucumber#138]
Hello, I've noticed that 'scenarioNameTemplate' option is not processing scenarios name if those scenario were defined as Scenario Outline

runner.js: (add tags to the scenario name name)
```js
import steps from '@logic/stepDefinitions';
import { autoBindSteps, loadFeatures } from 'jest-cucumber';

const features = loadFeatures('**/features/*.feature', {
  scenarioNameTemplate: (vars) => `${vars.scenarioTags} ${vars.scenarioTitle}`,
});

autoBindSteps(features, steps);
```

feature:
```
@tag
Scenario Outline: Some test
  Given: Bla bla <param>
  
  Examples: 
   | param |
   | 1          |
   | 2          |
 
@tag2
Scenario: Some test 2
  Given: Bla bla 1
   
```

scenarios names would be:

- Some test
- Some test
- @tag2 Some test 2

**Comment by norbertpeity** [comment]
I encountered the same problem, and tried the solution from this PR, and it looks like it fixes the issue:
https://github.com/bencompton/jest-cucumber/pull/144
