### ISSUE TITLE
Reusable steps with response from an async function

### ISSUE THREAD

**Issue by felixbuchholz** [bencompton/jest-cucumber#146]
Hi, thank you so much for this great package! 🎉 

I’m facing a problem, that I can’t wrap my head around.
My current setup requires a testRunner function provided by the backend framework that I’m using, [see this link](https://keystonejs.com/docs/guides/testing#writing-tests).

The runner function takes an async function as a parameter and returns a promise like this: 
``` TypeScript
const runner: (testFn: (testArgs: TestArgs) => Promise<void>) => () => Promise<void>
```

I want to share the testArgs across step definitions because they include a context object that I need to interact with the database.
I can easily do this: 

``` TypeScript
defineFeature(feature, test => {
  test('...', async ({ given, when, then }) => {
    let user = {}
    let context

    given('the database is reset', async () => {
      await runner(async ({ context: runnerContext }) => {
        context = runnerContext
      })()
    })

    given('I am the test user', async () => {
      const response = await createUser({
        context,
        variables: { data: { ...testUser } },
      })
      user = response.data.createUser
    })
...
```

But I really would love to separate out these as **reusable** steps and import them because I will need them in a lot of tests. But then of course context will always be undefined when I pass it down to the imported functions because it’s undefined in the test scope when these functions are initialized. 

Do you have any recommendations on how to deal with this? 

Thank you so much in advance!

**Comment by felixbuchholz** [comment]
I found a solution, with a function exposing a getState and setState function, similar to useState in React.

**Comment by tsargent** [comment]
@felixbuchholz can you explain a bit more how you solved this? I am facing the same problem with reusable steps and async behavior.

**Comment by felixbuchholz** [comment]
@tsargent sorry for the late reply. This was in a project while back and I was a bit busy this week.

Here’s how I implemented the getState (called `state` in the example) and setState functions. It’s not super sophisticated, but did the trick:

`testState.ts`:
``` TypeScript 
export type GetState<T> = () => T
export type SetState<T> = (newVal: T) => void

export const testState = <T>(initialValue: T): [GetState<T>, SetState<T>] => {
  let _val = initialValue // local
  const state = (): T => {
    // closure
    return _val // _val from outer function scope
  }
  const setState = (newVal: T): void => {
    _val = newVal
  }
  return [state, setState]
}
```


I’m using those functions as parameters for wrapper functions that define my individual steps. For setting up my context for example, `stepDefinitions/common/givenTheDatabaseIsReset.ts`:

``` TypeScript
import { GetState, SetState } from '../../utils/testState'

import { DefineStepFunction } from 'jest-cucumber'
import { KeystoneContext } from '@keystone-6/core/types'
import config from '../../../keystone'
import { setupTestEnv, TestEnv } from '@keystone-6/core/testing'

type Params = {
  given: DefineStepFunction
  getContext: GetState<KeystoneContext & { testEnv: TestEnv }>
  setContext: SetState<KeystoneContext & { testEnv: TestEnv }>
}

export const givenTheDatabaseIsReset = async ({
  given,
  getContext,
  setContext,
}: Params): Promise<void> => {
  given('the database is reset', async () => {
    const prevTestEnv = getContext()?.testEnv
    if (prevTestEnv) {
      await prevTestEnv.disconnect()
    }
    const testEnv = await setupTestEnv({ config })
    const context = { ...testEnv.testArgs.context, testEnv }
    setContext(context)
  })
}
```

Then I can reuse the context by calling getContext().
`stepDefinitions/common/givenIAmTheTestUser.ts`:

``` TypeScript
import {
  CreateUserMutation,
  createUser,
} from '../../../codegen/generated/generatedCucumber'

import { DefineStepFunction } from 'jest-cucumber'
import { KeystoneContext } from '@keystone-6/core/types'
import { SetState } from '../../utils/testState'

export const testUser = {
  // ...
}

export type Params = {
  given: DefineStepFunction
  getContext: () => KeystoneContext
  setTestUser?: SetState<CreateUserMutation['createUser']>
}

export const givenIAmTheTestUser = ({
  given,
  getContext,
  setTestUser,
}: Params): void => {
  given('I am the test user', async () => {
    const response = await createUser({
      context: getContext(),
      variables: { data: { ...testUser } },
    })
    if (setTestUser) {
      setTestUser(response.data.createUser)
    }
  })
}
```
Does this help?

**Comment by felixbuchholz** [comment]
Maybe two more pointers:

I’m using the autobind-feature, `jest-cucumber/stepDefinitions/cucumber.steps.ts`: 

``` TypeScript
import { autoBindSteps, loadFeatures } from 'jest-cucumber'
import { allSteps } from '../../codegen/generated/generatedCucumber'

const features = loadFeatures('jest-cucumber/features/**/*.feature')
autoBindSteps(features, [allSteps])

```

and I have set up a script to create functions based on my feature-files that collects them in a file,
`generatedCucumber.ts`:

``` TypeScript
const [getContext, setContext] = testState<
  KeystoneContext & { testEnv: TestEnv }
>(null)
const [getTestResponse, setTestResponse] = testState<any>(null)

export const allSteps: StepDefinitions = ({ given, when, then }) => {
  givenIAmTheUser({ given, getContext })
  givenTheDatabaseIsReset({ given, getContext, setContext })

  // ...
}
```

**Comment by tsargent** [comment]
Thank you @felixbuchholz !
