### ISSUE TITLE
Test ordering

### ISSUE THREAD

**Issue by cappelaere** [bencompton/jest-cucumber#15]
Is there a way we could preserve the order of the tests?
This would be a great feature for an acceptance test.
I tried to have the files in alphabetical/numeric order but it did not help.
Thanks.

**Comment by bencompton** [comment]
Jest is running your tests, so there isn't really anything I'm aware of that jest-cucumber can do to control the execution order. I see there is actually an [open issue](https://github.com/facebook/jest/issues/6194) in the Jest repo about this very topic.

Is your motivation primarily aesthetic, or do your scenarios depend on a particular execution order? For the latter case, I'm sure there are perfectly valid exceptions, but I generally follow the rule of having no shared state between tests so they can all execute independently and more reliably.

**Comment by cappelaere** [comment]
I came up with a solution... get jest to ignore the steps.js files in the steps directory but use the index.js in that directory.
Then in steps/index.js:
const step1 = require('./1.steps');
const step2 = require('./2.steps');
const step3 = require('./3.steps');
const step4 = require('./4.steps');
const step5 = require('./5.steps');
const step6 = require('./6.steps');
const step7 = require('./7.steps');

**Comment by bencompton** [comment]
That's interesting, I can certainly understand your challenge there. Glad you were able to find a solution that works for you.
