### ISSUE TITLE
How to run with WebStorm?

### ISSUE THREAD

**Issue by hejkerooo** [bencompton/jest-cucumber#152]
Is there any way to run tests using Webstorm?
I've tried to wrap `defineFeature` with `describe` but jest-cucumber fails in that case to load feature files
Thanks!

**Comment by lnhrdt** [comment]
@hejkerooo I see you marked this as completed, how were you able to run tests using Webstorm?

**Comment by hejkerooo** [comment]
@lnhrdt 

Sorry for late answer - I've wrapped tests in `describe` so I can run them from WebStorm. 

i.e.

`describe('Test', () => {
  defineFeature(feature, () => {
    test(...)
  })
  })
  `
  
  It lets me to run series of tests, not specific one but it's always something.

**Comment by lnhrdt** [comment]
Yes! It's so simple but I never saw found this solution on my own. I've been just dealing with it by running tests in my terminal for the last 8 months. Now I can run jest-cucumber tests in my IDE (IntelliJ in my case). 🎉

Thanks so much @hejkerooo for circling back to this issue to share, even after all this time.
