### ISSUE TITLE
 jest-cucumber : Feature file not found () error

### ISSUE THREAD

**Issue by santhazh1** [bencompton/jest-cucumber#155]
I have a feature file , named as consoleLogger.feature.

and consoleLogger.steps.js which contains the below code ,

import { defineFeature, loadFeature } from 'jest-cucumber';
const consoleLogger = require('../src/Util/consoleLogger');
const feature = loadFeature('../feature/consoleLogger.feature');

I am trying to connect feature file with step file using loadFeature but getting the below error ,
 FAIL steps/consoleLogger.steps.js ● Test suite failed to run

Feature file not found (C:\Users\sr00015\NewWorkspace\feature\consoleLogger.feature)

folder structure 
![image](https://user-images.githubusercontent.com/106539548/177991081-0f90c1f0-2cbb-41f0-b510-125777b92b3e.png)

**Comment by IvaanTorres** [comment]
I had the same error.
You must specify the path from the root directory.
Example: ./feature/consoleLogger.feature

**Comment by AnserJoe** [comment]
I had the same error.
I must use a relative path，Please repair it as soon as possible

**Comment by AnserJoe** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/28861986/227090417-965b3aee-c02b-4588-b62f-a54470ebe653.png">
add the option "{loadRelativePath: true}"
