### ISSUE TITLE
Can't test the front-end using testing library

### ISSUE THREAD

**Issue by IvaanTorres** [bencompton/jest-cucumber#158]
I've been configuring jest-cucumber to set it up in my project (NextJS), however, I realized that jest-cucumber just work if I set up Jest with -> testEnvironment="Node".
It works if I just test mathematical functions, however, in case I try to render some React components, it just crashes.
I'm wondering if jest-cucumber has been developed for server side and not for the front-end.

Here the output and my setup:
Jest config:
![config](https://user-images.githubusercontent.com/72036570/183965837-bf29478f-d321-4303-98d1-3e89affe615b.PNG)

jest-cucumber setup file (without it, the test fails as well):
![setup file](https://user-images.githubusercontent.com/72036570/183966033-4777b36e-ff91-4bdc-8101-4de5b79e7293.PNG)

The test example using React Testing Library:
![test](https://user-images.githubusercontent.com/72036570/183966097-33c6f049-4f2a-44fb-8b7e-33f39c4c6171.PNG)

The output of the test:
![output](https://user-images.githubusercontent.com/72036570/183966136-9eccba30-5ca6-4af3-9a53-436f8788336e.PNG)

<> - I installed all the main packages such as ts-jest, etc to transform the main files.
<> - I'm using some testing tools besides jest-cucumber such as Jest and React Testing Library.

Thanks for the help

**Comment by alecat88** [comment]
> ** Update ** You can use the package called "jsdom-global" so you can render a dom in nodejs You just have to require it in every test since Jest has to be configured to use "Node" as testEnvironment

Do you have an example? I've tried to require it but it's still not working for me
