### ISSUE TITLE
How to execute then block after async when block

### ISSUE THREAD

**Issue by nitinmagdumvista** [bencompton/jest-cucumber#159]
test('Get Container failure with invalid container id', ({
  given,
  when,
  then,
}) => {
  let error;
  
given('Container does not exist with given container id', () => {
    mockContainersService.getContainerById = jest
      .fn()
      .mockRejectedValue(new NotFoundException());
  });
  
when('I call get container by id method', () => {
    controller
      .getContainerById(containersIdentifierDTO, mockRequest)
      .catch((err) => {
        error = err;
      });
  });
  
then('I should be getting container not found with given id', () => {
    expect(error.message).toBe('NOT FOUND');
  });
});

//==================================

I want to execute then block after result of when block 
in above example i am testing error scenario in jest. i am mocking method in given block and and calling in when block and its result is stored in error variable which i am validating in then block but the issue is that then block is getting executed before when block async method executes.

**Comment by nitinmagdumvista** [comment]
@bencompton

**Comment by robinelvin** [comment]
I think the simplest way is to return the Promise in the `when` method. The test runner will await this before executing the next step, in this case the `then` method.

**Comment by nitinmagdumvista** [comment]
@robinelvin Thanks a lot its working

when('I call get container by id method', async () => {
      return await controller
        .getContainerById(containersIdentifierDTO, mockRequest)
        .catch((err) => {
          error = err;
        });
    });

**Comment by nitinmagdumvista** [comment]
`when('I call get container by id method', async () => {
      return await controller
        .getContainerById(containersIdentifierDTO, mockRequest)
        .catch((err) => {
          error = err;
        });
    });`

**Comment by robinelvin** [comment]
> @robinelvin Thanks a lot its working
> 
> when('I call get container by id method', async () => { return await controller .getContainerById(containersIdentifierDTO, mockRequest) .catch((err) => { error = err; }); });

Glad you got it sorted. I'm surprised this works as I thought promise rejections caused the test step to fail but I haven't checked this.

**Comment by nitinmagdumvista** [comment]
Check solution above
