### ISSUE TITLE
Test Run Results Reporting - Cucumber JSON

### ISSUE THREAD

**Issue by darkhorse93** [bencompton/jest-cucumber#17]
Hi, 

Have gone through docs, didn't find any thing on results reporting front. Is there anyway we can generate run result reports with all the test run features and their status. 

Does jest-cucumber generate cucumber json file after every run where we can use it to generate HTML reports with the run results. 

Thanks.

**Comment by bencompton** [comment]
Hi @darkhorse93. Reporting is out of scope for this library, and is instead accomplished with reporting plug-ins for Jest itself. For example, I have had a lot of success with [jest-junit](https://github.com/jest-community/jest-junit#readme). Hope that helps!

**Comment by bencompton** [comment]
@darkhorse93 - if you're specifically asking about Cucumber JSON, I actually don't know of any current way to accommodate that with existing tooling. As far as HTML output, [Pickles](http://www.picklesdoc.com/) has worked fairly well for me for generating a searchable HTML page to publish as a living documentation website. Is something like [this ](http://www.picklesdoc.com/pickles/Output/Dhtml/Index.html?feature=Features%5C00BasicGherkin%5CBasicGherkin.feature) what you're ultimately trying to accomplish?

**Comment by darkhorse93** [comment]
Thanks @bencompton for the clarification. We are currently using the jest-junit, and wanted cucumber style html reports . Thanks for your suggestion on pickles will look into it.

**Comment by kimthanhMillergold** [comment]
Hi , I have tried jest-cucumber but it always generate test report very general as follows
 Feature
     Scenario 1 : passed
     Scenario 2: passed 
How could i generate test report include steps and label which is passed or fail on steps ?

**Comment by bencompton** [comment]
@kimthanhMillergold, having detail beyond the scenario level is currently not supported. There will need to be a special plug-in for jest-cucumber to accomplish that.

**Comment by bencompton** [comment]
#27 is an enhancement in the backlog to address this, so closing this one.
