### ISSUE TITLE
gherkin dependencies is not same in package.json inside node_modules and individual jest-cucumber project.

### ISSUE THREAD

**Issue by vamshireddycvs** [bencompton/jest-cucumber#171]
While we add jest-cucumber:3.0.1 as devDependencies in our project. after npm install, compare package.json of jest-cucumber which is present inside node_modules and individuals download jest-cucumber package.json. we found different gherkin name

inside node_modules package.json found  "gherkin": "^9.0.0",

and  individuals download jest-cucumber package.json found @cucumber/gherkin": "^17.0.0"

so, please validate why above statement is happen.

**Comment by pplancq** [comment]
@vamshireddycvs  This has been corrected with the release of the new version 4.0.4


This issue can be closed
