### ISSUE TITLE
Retry steps

### ISSUE THREAD

**Issue by mpontus** [bencompton/jest-cucumber#172]
Hi. I've using cucumber-js to test infrastructure after deployment. Most of the scenarios involve eventually-consistent service, so virtually every step has to be attempted multiple times before it is successful.

With cucumber-js, I was able to use [setDefinitionFunctionWrapper](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md#setdefinitionfunctionwrapperwrapper) to implement retry logic on every step without changing step definitions. 

I'm wondering if you have plans to support a similar kind of configuration for jest-cucumber or maybe an option to set per-step retry attempts?

**Comment by Odonno** [comment]
This can indeed be really helpful to flag flaky steps like previously described. Can't that feature be added to the backlog?
