### ISSUE TITLE
Change given, when and then to uppercase

### ISSUE THREAD

**Issue by thelinuxlich** [bencompton/jest-cucumber#173]
The Cucumber official VSCode extension doesn't recognize steps in lowercase :(

**Comment by jagoral** [comment]
@thelinuxlich have you found any workaround to use the official Cucumber extension? I'm struggle also with this issue, and although we are quite satisfied with `jest-cucumber`, we miss ability to use the extension :(

**Comment by thelinuxlich** [comment]
I ended up using another extension

**Comment by xuanngo2001** [comment]
@thelinuxlich 
Which extension did you use?

**Comment by thelinuxlich** [comment]
This one: https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete
