### ISSUE TITLE
Is alive ?

### ISSUE THREAD

**Issue by pplancq** [bencompton/jest-cucumber#175]
Hello,

Is this library still maintained ?

last commit Jan 21, 2022
last release published 2 years ago

**Comment by jclaveau** [comment]
The most alive project, but quite early, I see for now is this one: https://github.com/samuel-ziegler/vitest-cucumber-plugin

There is also this one but it seems dead also https://github.com/mainfraame/cucumber-jest

**Comment by silence-coding** [comment]
@bencomptonExcuse me, is this project still under maintenance?

**Comment by pplancq** [comment]
Announcing the Continuation of jest-cucumber #183

**Comment by bencompton** [comment]
My apologies to the community. This package is getting over 1M downloads per month these days, and I’m honored it has been so useful to that many devs out there. I’ve been a bad maintainer and haven’t kept this package up to date, but I will say that I’m still passionate about the DevEx this package enables and don’t want to abandon it. I’ve been away from the web development world the last couple of years and life has been especially busy, but I’ve really missed being able to use this package when doing Cucumber tests in other languages recently.

I’d really like to keep this package going, so today, I’ve taken some steps to more easily keep things up to date: I’ve enabled Dependabot, updated everything to support Jest 29, added automation for publishing packages, and created reminders for myself look at this repo at least monthly to take care of any necessary updates. I hope to do more in the future, and even expand this DevEx into other programming languages, but for now, I suppose I can at least make sure the latest version of Jest continues to be supported and any vulnerabilities are addressed at the very least.

v4.0.1 is now published to NPM for the community to enjoy.

**Comment by pplancq** [comment]
Dear @bencompton,

I was delighted to read your message and learn of the recent updates and your renewed commitment to the package. It's wonderful to see your passion for improving the developer experience (DevEx) shine through, and I wholeheartedly support your efforts.
Please know that there is no judgment on my part regarding the maintenance hiatus; life is full and we all have our journeys. What matters is the positive impact your work has had on many developers, myself included.

With the return of active development of the package, I'm looking forward to contributing and bringing you the updates I'd envisioned. I look forward to collaborating directly on the repository and being part of its continued success.

Thank you for your dedication and for sharing v4.0.1 with the community. I wish you many more milestones!
Warm regards.

**Comment by TKwakernaak** [comment]
Great to hear that this package is still getting attention. Thank you for your efforts.

**Comment by mateuszmatyszkowicz** [comment]
You made my day! I was super surprised that version 3.0.2 was appeard when I did yarn upgrade and even more when I noticed that there is 4 released. Finger crossed!
