### ISSUE TITLE
Update jest dependencies and publish new version

### ISSUE THREAD

**Issue by timvandenhof** [bencompton/jest-cucumber#178]
Please update the following dependencies, as that will fix some deprecation warnings that are visible after taking a dependency on `jest-cucumber`:

- Replace `gherkin` with `@cucumber/gherkin`: <-- Already fixed in preview version 3.0.2
> WARN  deprecated gherkin@9.0.0: This package is now published under @cucumber/gherkin
> WARN  deprecated cucumber-messages@8.0.0: This package is now published under @cucumber/messages
> WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

- Update jest related dependencies to latest version:
>  WARN  deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> WARN  deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
> WARN  deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> WARN  deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> WARN  deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> WARN  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

**Comment by timvandenhof** [comment]
There seems to be an open PR to fix some of these issues: #170

**Comment by timvandenhof** [comment]
@bencompton Sorry for the direct mention, but is the `jest-cucumber` project still alive or should we start switching to a different solution instead?

**Comment by valtersantosmatosmanulife** [comment]
Same question here :) haven't seen much activity

**Comment by pplancq** [comment]
Announcing the Continuation of jest-cucumber #183

**Comment by bencompton** [comment]
See this [issue comment](https://github.com/bencompton/jest-cucumber/issues/175#issuecomment-2016323250).
