### ISSUE TITLE
Announcing the Continuation of jest-cucumber

### ISSUE THREAD

**Issue by pplancq** [bencompton/jest-cucumber#183]
Hello everyone,

I wanted to inform you that due to the discontinuation of maintenance by the original author of jest-cucumber, which I respect, I have decided to fork the project and take over its maintenance. You can find the new project here: [cucumber-runner](https://github.com/pplancq/cucumber-runner).

I plan to release a v1.0.0 version soon, which will initially be a simple update of the codebase (dependencies, linting, etc.) without the addition of new features. This is intended to facilitate the transition for existing projects.

Following this, new features and bug fixes will be added as usual.

I will keep you updated on the progress of this project.

Thank you for your understanding and support.

**Comment by bencompton** [comment]
See this [issue comment](https://github.com/bencompton/jest-cucumber/issues/175#issuecomment-2016323250).
