### ISSUE TITLE
Dynamic scenario outline titles

### ISSUE THREAD

**Issue by duylddev** [bencompton/jest-cucumber#19]
Jest report the same title in different scenario.
How to use variable in scenario title?

![image](https://user-images.githubusercontent.com/9783862/43787705-cff14b24-9a95-11e8-9456-9ab0f2b5f5df.png)
![image](https://user-images.githubusercontent.com/9783862/43787731-e01b5300-9a95-11e8-9ef6-307e621db359.png)
![image](https://user-images.githubusercontent.com/9783862/43787803-12b01a8a-9a96-11e8-8e4a-84b51ec188db.png)

**Comment by bencompton** [comment]
This behavior is not currently supported, but would certainly be useful. This is related to #7, and jest-cucumber needs some work to support more dynamic replacement values in scenario outlines overall.

**Comment by duylddev** [comment]
Thanks for reply. 
Did you have plan for this?

**Comment by bencompton** [comment]
Yeah, this sounds like a good feature to add. I tagged it as an enhancement for the backlog, so let's leave this issue open.

**Comment by bencompton** [comment]
Fixed in #21
