### ISSUE TITLE
Error in Release Workflow Configuration

### ISSUE THREAD

**Issue by pplancq** [bencompton/jest-cucumber#213]
I've noticed an error in the release workflow that I've set up. 

![image](https://github.com/bencompton/jest-cucumber/assets/107397730/65b2ca66-a74a-43c6-806f-274ff2801689)

After analyzing the error, I realized that I made a mistake in the configuration. Specifically, the `semantic-release` configuration I've set up is fixed on the `main` branch, but this repository uses `master` as the primary branch.

![image](https://github.com/bencompton/jest-cucumber/assets/107397730/90e08576-9a9c-4bea-a5a0-7a1090d4ab74)

I propose two solutions:

1. Rename the `master` branch to `main`.
2. I quickly create a PR to correct the `semantic-release` configuration.

I'm open to other suggestions and look forward to resolving this issue promptly.

**Comment by bencompton** [comment]
Hey, appreciate you looking into it! I'll try renaming the branch and see if that fixes it, then.

**Comment by pplancq** [comment]
Following the renaming of the master branch to main, the release workflow problem has been corrected.
I'm closing this issue.
