### ISSUE TITLE
Upgrade `@cucumber/gherkin` from v17 to v28

### ISSUE THREAD

**Issue by ychavoya** [bencompton/jest-cucumber#214]
I noticed that the dependency `@cucumber/gherkin` has not been upgraded in this project since around 3 years ago (currently using v17). It would be good to try to perform this upgrade. I have tried to manually override the version, but it seems to have been a breaking change somewhere in-between, so it looks like the code would need some changes.

```
  ● Test suite failed to run

    Error parsing feature Gherkin: Cannot read properties of undefined (reading 'reset')

      84 | testedFeatures.forEach(feature => {
      85 |   defineFeature(
    > 86 |     loadFeature(feature.file),
         |                ^
      87 |     definition
      88 |   );
      89 | });

      at parseFeature (node_modules/jest-cucumber/src/parsed-feature-loading.ts:328:11)
      at loadFeature (node_modules/jest-cucumber/src/parsed-feature-loading.ts:354:24)
```

**Comment by bencompton** [comment]
Last time I updated it, the Cucumber reporting feature this library used to have needed to be removed because it changed so drastically, and it continues to introduce breaking changes. Agreed that updating it would be good so the latest features are available to leverage, at least.

**Comment by ychavoya** [comment]
Thanks @bencompton, I am willing to contribute with this upgrade

**Comment by bencompton** [comment]
Definitely would appreciate a PR to upgrade, assuming the required changes don't involve a major and risky rework of all of the code or something.
