### ISSUE TITLE
Scenarios not running

### ISSUE THREAD

**Issue by robinelvin** [bencompton/jest-cucumber#22]
I have a project to which I've been happily adding scenarios and test steps. I have just added a couple of scenarios to a feature, run the test and jest-cucumber has duly printed the skeleton code for the steps.

Upon adding these steps the test now passes but these scenarios appear not to be running. If I remove all the step definitions from the `test(...)` function it still doesn't show this test as running nor that the steps are missing. If I add a `pending()` to a step then it now shows the test as skipped. If I change the `pending()` to a `console.log(...)` the test is not shown as running nor is the console output printed.

I don't know how to debug this further short of pulling the jest-cucumber code apart. Do you have any ideas?

**Comment by bencompton** [comment]
This is fixed in version 2.0.2 on NPM, which is currently a beta version (tagged @next). Thanks for reporting!
