### ISSUE TITLE
Duplicate step definitions with parameters are not matched correctly

### ISSUE THREAD

**Issue by robinelvin** [bencompton/jest-cucumber#24]
With the following Scenario:

```
    Scenario: Check a list of things
        Given the list of things contains 3 things
        And thing 1 has the following data:
            | id | name   |
            | 1  | First  |
        And thing 2 has the following data:
            | id | name   |
            | 1  | First  |
            | 2  | Second |
        And thing 3 has the following data:
            | id | name   |
            | 2  | Second |

```

jest-cucumber suggests the following step definitions:

```
test('The list of things', ({ given, when, then, pending }) => {
        given('Given the list of things contains (.*) things', (arg0) => {
            pending();
        });
    
    	given(/^thing (.*) has the following data:$/, (arg0, table) => {
            pending();
        });
    
    	given(/^thing (.*) has the following data:$/, (arg0, table) => {
            pending();
        });
    
    	given(/^thing (.*) has the following data:$/, (arg0, table) => {
            pending();
        });
    });
```

There should only be a single `given` for the `thing (.*) has the following data:` step. Additionally if you only put a single `given` in the steps file the scenario runner complains that it matches multiple steps in the feature.

**Comment by bencompton** [comment]
One difference from Cucumber is that a single step definition can't match multiple steps, and instead the step definitions must exactly match the feature file for each scenario. This allows the steps to read like the feature file and be simpler to reason about. I have seen that this is a common gripe with Cucumber--that the step definitions can be spread all over the place and it can be hard to figure out what matches what, especially as the size of a project grows. To keep the code more DRY, it is recommended that you move step definition code into separate functions as described [here](https://github.com/bencompton/jest-cucumber/blob/master/docs/ReusingStepDefinitions.md). Just like with Cucumber, you can still build libraries of re-usable step definitions, but you have to import them and explicitly call them in each scenario where they are used.

I suppose it would be good if the step generator at least were smart enough to automatically encapsulate duplicate steps in a function automatically in the generated code.

I have heard feedback that some people aren't big fans of the way jest-cucumber requires step definitions to match the feature file exactly. If you're in that camp, or have any ideas for improvement, please feel free to weigh in.

**Comment by robinelvin** [comment]
Unfortunately the problem persists even when you move the step definitions to separate functions. As far as I can see the issue is when you have duplicate steps in the _same_ scenario.
I've just had this come up again with

```
And I should see a button labelled "OK"
And I should see a button labelled "Cancel"
```

which throws this error:

`"/^I should see a button labelled (.*)$/" matches 2 steps in the feature file scenario, "See the hero section"`

Unless I'm missing something here I can't see how this should work. Using a shared step definition does the same thing. The only way around it at the moment is something like:

`And I should see buttons labelled "OK" and "Cancel"`

**Comment by martotkd1** [comment]
Can you write it like this:
"/^I should see a button labeled (OK|Cancel)$/" ... (option) => {... }

**Comment by martotkd1** [comment]
it's not working.
@bencompton could you please let me know if you have any plan when you will have the time to fix it ? This issue introduces duplication especially when most of your steps are using (A|B|C|D).. and without re-using the steps is not okay.

**Comment by viqashussain** [comment]
@bencompton  I am also having an issue with this, please let us know if there is/will be a solution.

**Comment by bencompton** [comment]
Fixed in v1.0.11. It will now not cause errors when a step definition matches more than one step. Validation will now only check that the number of steps match between the step definitions and feature file, and that each step definition matches its corresponding step in the feature file. Checking that each step definition only matches a single step in the scenario is superfluous.

It would also be nice to improve the code generation to consolidate duplicate step definitions and automatically abstract them into a separate function, but that will have to be a project for another day.

@robinelvin, thanks for taking the time to define the problem so clearly.

**Comment by martotkd1** [comment]
@bencompton Great, thanks. Tried it out and works like a charm!

By the way i showed jest-cucumber to my teammates and we are going to use it for our integration tests for microservices.

Regards,
Martin

**Comment by bencompton** [comment]
@martotkd1 - glad it worked for you, and glad the library is providing value for you and your team!
