### ISSUE TITLE
Jest-Reports on a step level

### ISSUE THREAD

**Issue by elmolicious** [bencompton/jest-cucumber#26]
Hi,

I just searched the open/closed issues for this package and found one which describes a similar problem to the one I have. (#14)

BUT I do not really care about some IDE highlighting but need it for the generated reports.

> "Accomplishing that would require either restructuring the API so that every step can be a separate test "

Without that feature I feel its impossible to generate reports via jest which have a detailed overview on
- which step in a scenario failed
- how long individual steps took

Im looking into jest-cucumber right now (with jest-puppeteer) in order to replace the whole nightwatch (nightwatch-cucumber + selenium) stack for my acceptance / end-2-end test and loosing this detailed level of reports would be a great loss.

So, is there any way to get jest reports on a step level / are you planing on solving this / can one contribute to achieve this ?

Thanks for the reply in advance,
Best regards
Robin

**Comment by bencompton** [comment]
One option I have thought about is to create a separate library with a test results processor plug-in for jest-cucumber that would output Cucumber JSON. Jest test results processors appear to be fairly simple to write--just a function that looks like this and gets called after all of the tests execute:

```javascript
module.exports = (results) => {
  // TODO: Process test results, pull in step definition info, create JSON, and write to a file
}
```

jest-cucumber would need to keep track of errors and run-times for individual steps, and plumb this data into the reporter somehow. Worst case scenario, jest-cucumber could write out console logs with this info, and the console logs for each test (i.e., each jest-cucumber scenario) are available in the results for each test that get passed into the results processor function.

**Comment by elmolicious** [comment]
Well even if this sounds like it could work I am not quite sure if you want to choose the "dirty" way by adding the custom collected output in the result processor and recreating functionality which is normally covered by jest itself.

I understand that reworking the package to define steps as seperate tests steps is some work to do and maybe introduce other problems but I guess this would be the best solution for me.

To be honest I think I would rather write my tests without cucumber for now and revisit this problem later if I can keep my reports nearly the same for now.

Thanks for your thoughts about that anyway

**Comment by bencompton** [comment]
Thanks for the feedback. As you mentioned, restructuring the library so that each step is a separate test would create some problems. Jest executes tests in parallel, so there is way to guarantee that the scenario steps would get executed in order without sacrificing parallelism. Also, the VS Code tooling would have no easy way of debugging all steps in a scenario at once. The custom reporter is not 100% ideal either, but existing Jest reporters don't really fully accommodate Cucumber tests either.
