### ISSUE TITLE
Fails with "Feature file not found"

### ISSUE THREAD

**Issue by fbraz** [bencompton/jest-cucumber#31]
Hi. When I run jest against your example project I get the following error: 

```bash
npm run test                                                                                            master-?

> @ test /home/ferbraz/Documents/Code/jest-cucumber-test
> jest --color

 FAIL  specs/step-definitions/basic-scenarios.steps.js
  ● Test suite failed to run

    Feature file not found (/home/ferbraz/Documents/Code/features/basic-scenarios.feature)

      3 | import { Rocket } from '../../src/rocket';
      4 |
    > 5 | const feature = loadFeature('../features/basic-scenarios.feature');
        |                 ^
      6 |
      7 | defineFeature(feature, test => {
      8 |     test('Launching a SpaceX rocket', ({ given, when, then }) => {

      at Object.<anonymous>.exports.loadFeature (node_modules/jest-cucumber/src/parsed-feature-loading.ts:194:15)
      at Object.<anonymous> (specs/step-definitions/basic-scenarios.steps.js:5:17)
```

I created a repository so you can check this out if you need to do so: [https://github.com/fbraz/cucumber-test](https://github.com/fbraz/cucumber-test).

**Comment by bencompton** [comment]
The path to your feature file is actually not a relative path from the file where it is being consumed, and is instead is a relative path from the root of your project. If you look at [one of the examples](https://github.com/bencompton/jest-cucumber/blob/master/examples/typescript/specs/step-definitions/basic-scenarios.steps.ts), you'll see this in action:

```javascript
const feature = loadFeature('./examples/typescript/specs/features/basic-scenarios.feature');
```

I suppose this is less intuitive than having it be a relative path from where it is being consumed, and perhaps this should be changed.

**Comment by fbraz** [comment]
Thank you very much Ben.
