### ISSUE TITLE
Tag expressions

### ISSUE THREAD

**Issue by ussuritiger** [bencompton/jest-cucumber#32]
It would be nice if the library is able to support Cucumber tag expression as explained in [Cucumber documentation](https://docs.cucumber.io/cucumber/api/#tags) e.g. `(@smoke or @ui) and (not @slow)` as a value of `tagFilter`. Any plans to add this or maybe there is a way to do this that I've overlooked? Thanks.

**Comment by bencompton** [comment]
Agreed, would be a great feature!

**Comment by bencompton** [comment]
This is now available in version 2.0.2 on NPM, which is currently a beta version (tagged @next). Closing this issue, since #29 is related and we can use that one to track the progress of the beta.

**Comment by ussuritiger** [comment]
Thanks @bencompton for the update. I've upgraded up to 2.0.2 and trying to use this tag filter `not @e2e` so I want to execute all scenarios except the ones tagged with `@e2e`. However e2e scenarios are still executed. Any ideas?
