### ISSUE TITLE
Support for And keyword

### ISSUE THREAD

**Issue by kimeriksson75** [bencompton/jest-cucumber#38]
Would be nice if the ```and``` keyword could work as in mocha-cakes-2.

**Comment by kimeriksson75** [comment]
Would be nice if the ```and``` keyword could work as in mocha-cakes-2.

**Comment by bencompton** [comment]
All of the keywords are are just alternates for the the `defineStep` function, so adding `and` and `but` should be simple to do.

**Comment by NathanDrussell** [comment]
Created a PR(#41 ) implementing the feature

**Comment by bencompton** [comment]
I added support for the `but` keyword as well and updated the step definition generation code to generate the steps with `and` and `but` where appropriate. This is published in version 2.0.2 on NPM, which is currently a beta version (tagged @next).
