### ISSUE TITLE
How to load multiple feature file or execute group of features 

### ISSUE THREAD

**Issue by UsharaniA** [bencompton/jest-cucumber#40]
Hi,
I want to execute group of features files through jest cucumber package and i see currently it allows only one feature to be loaded.

const feature=loadfeature('**/firstfeature.feature')

**Comment by bencompton** [comment]
Yes, each call to `loadFeature` will load one feature file. Typically, you will have one step definition file per feature file and call `loadFeature` in each step definition file. Did you have another use case in mind?

**Comment by UsharaniA** [comment]
Ok,
I have few test cases which have same definition and i don't want to repeat the feature file creation and step definition creation  for each so if i though if i have step definition i can create multiple feature and invoke them for all

**Comment by UsharaniA** [comment]
Also i have a issue ,below is my defibition

when(/^the user loginto ART with credential from "([^"]*)" and "([^"]*)" column from spreadsheet$/,  () => {
      return queryRedshift.dbValidate();
   
    });

    when(/^the user selects client as value from "([^"]*)" column and account structure from "([^"]*)" column and datarange from "([^"]*)" column and View as Paid$/, async (pclient,paccountStructureName, pdateRange, pviewSelect) => {
     
       console.log("The user selects account structure");
    });

    then(/^the user read date and funding arrangement from ART screen and store in Config file$/,async() =>{
       await console.log("The user selects account structure");
    });
   

i can see before the first when is complete the test is moving to other When and then , how can i fix them

**Comment by UsharaniA** [comment]
Thanks i fixed my promise issue and now it works.

**Comment by UsharaniA** [comment]
I see   "jest-html-reporter": "^2.4.2" produces html reports of the pass fail steps  but it gives the details of only the test annotation and not the Given,When, then closed under test annotation,please let me know if am missing anything and also let me know if i can attach screenshot and test steps .
![image](https://user-images.githubusercontent.com/24645320/49630030-6f644e00-fa12-11e8-8e49-5ed895a1a649.png)


My feature file:
Scenario:ValidateTrendAmbulatoryCondition
Given the testcase is "ValidateTrendAmbulatoryCondition"
When the user loginto ART with credential from "pUserName" and "pPassword" column from spreadsheet  
When the user selects client as value from "pClient" column and account structure from "pAccountTitle" column and datarange from "pDateRange" column and View as Paid
When the user read date and funding arrangement from ART screen and store in Config file
When the user navigate to Dashboard Pathway and select dashboard as from "pDashboardName" column 
Then use the dashboard object "ambulatorycondition" from repository and edit the dashboard in Visualizer and render the Data from BIRST
When the user loginto to Redshift
Then user fires Query and retrive data from Redshift and store it in Excel and compare the data


But i dont see all this details in the html report

**Comment by bencompton** [comment]
Glad it worked for you! As for reporting, existing Jest reports don't show step info, since that's unique to jest-cucumber and not a general Jest feature. A specialized reporting plug-in is planned. See #17 and #27.

Sounds like your issue is good to go, so I'm going to close this issue.
