### ISSUE TITLE
tagFilter and errorOnMissingScenariosAndSteps do not seem to be compatible with each other?

### ISSUE THREAD

**Issue by njpbjss** [bencompton/jest-cucumber#42]
If I want to run a subset of feature scenarios with the tag @foo, I would write something like:

`const feature = loadFeature('myfeature.feature', { tagFilter: ['@foo'] });`

In which case, the tagged scenarios run, but I get errors that no matching feature is implemented because the steps are present in the file but the features are filtered out.

The documentation indicates that to get around this, we can write:

`const feature = loadFeature('myfeature.feature', { tagFilter: ['@foo'], errorOnMissingScenariosAndSteps: false });`

But when I run this, *all* the tests run, as if it was ignoring tagFilter completely. Could you advise?

**Comment by Srutherford2407** [comment]
@njpbjss Please see #29 he is aware and currently working to resolve the issues with the tag features. My comments on that issue should help cover your questions and the future of this feature!

**Comment by njpbjss** [comment]
Makes sense; upgrading to 2.0.0 will do the trick for now. Much appreciated!
