### ISSUE TITLE
loadFeature checks based on project location, not file location

### ISSUE THREAD

**Issue by dbartholomae** [bencompton/jest-cucumber#43]
## How it is ##
`loadFeature()` requires a path relative to the package root: let's assume `package.json` is in `/`, the test file in `/src/feature/test.steps.js` and the feature file in `/src/feature/test.feature` then the line required to load the feature into the test is
```
const feature = loadFeature("./src/feature/test.feature");
```

## How it should be ##
It should be
```
const feature = loadFeature("./test.feature");
```

## Reproducing repo ##
See e. g. this repo:
https://github.com/spirosikmd/jest-cucumber-puppeteer-example/blob/master/test/manage-todo-list.steps.js

## Comments ##
I would be willing to help with a PR, but we need to figure out how to avoid a breaking change.

**Comment by dbartholomae** [comment]
Does it make sense for me to create a PR?

**Comment by bencompton** [comment]
@dbartholomae - yes, I would be quite thrilled to see a PR for this issue if you'd like to give it a try!

**Comment by dbartholomae** [comment]
I've added a PR. It adds the feature optionally so there is no breaking change and you can release right away. Since there is no test suite I've tested it by changing the code in the example files. I've changed it back though as it isn't the default interface.
If you want to have this the default behavior in the next breaking version, I would suggesting simply changing the `loadRelativePath` flag to `loadAbsolutePath` in the code and the documentation.
