### ISSUE TITLE
Moving steps outside of defineFeature scope

### ISSUE THREAD

**Issue by Maxim-Filimonov** [bencompton/jest-cucumber#44]
Hi,
Great library overall and enables us to use wallabyjs which helps a lot to understand our codebase coverage and get feedback very fast unlike cucumber.
However, as we tried to move our steps definitions outside of `defineFeatures` as we are reusing step definitions across many different features.
It looks like beforeEach runs after test which prevents us from being able to use instance instantiated in beforeEach. Here is a simplified example of what we are trying to do:
```
class Steps {
  public counter: number;
  constructor() {
    // We can defined Given for this, however our setup code is not as simple as that.
    this.counter = 0;
  }
  public addOneCounter(this: any, when: any) {
    when('I add one to counter', function(this: any, value: string) {
      this.counter += 1;
      console.log('COUNTER:', this.counter);
    });
  }
  public counterShouldEqual(this: any, then: any) {
    then(/^the counter should equal (.*)$/, function(this: any, expected: string) {
      expect(this.counter).toEqual(parseInt(expected, 2));
    });
  }
}
defineFeature(feature, (test) => {
  beforeEach(function(this: any) {
    this.steps = new Steps();
  });
  test('Step should be allowed to be outside', function(this: any, { when, and, then }) {
    this.steps.addOneCounter(when);
    this.steps.addOneCounter(and);

    this.steps.counterShouldEqual(then);
  });
});
```

**Comment by Maxim-Filimonov** [comment]
@bencompton second argument is Typescript announance. As it requires to define type of this :[
My initial code was instantiating steps inside the test function, just like you did. 
However, the problem with that approach is that it doesn't work with examples.
If you try to use this example with scenario outline you will notice that counter instance gets shared between all examples as constructor is only called once.

**Comment by bencompton** [comment]
Yes, I suppose that wouldn't work well with scenario outlines. Your class has two purposes: to register your step definitions (calling given, when, then), and to hold state that is unique to each test run. Once your step definition functions are registered, they exist only in a specific instance of the class, so re-instantiating the class isn't really an option. The only option that comes to mind for scenario outlines would be to have a method that resets the state of your class that you call in `beforeEach`.

I'm sure you were hoping for a better answer than that. jest-cucumber wasn't really designed to work like SpecFlow, for example, where the step definitions and test state are stored in the same class, and the class gets re-instantiated for every test run. To make it work like that would require some pretty major changes.

**Comment by Maxim-Filimonov** [comment]
Okay, I think that works:
```
defineFeature(feature, (test) => {
  const steps = new Steps();
  beforeEach(function(this: any) {
    steps.resetCounter();
  });
  test('Step should be repeated 2 times when specified twice', ({ when, and, then }) => {
    steps.addOneCounter(when);
    steps.addOneCounter(and);

    steps.counterShouldEqual(then);
  });
});
```
For step definitions I need to switch to arrow functions to access `this`:
```
class Steps {
  public counter: number;
  constructor() {
    this.counter = 0;
  }
  public resetCounter() {
    console.log('RESETTING');
    this.counter = 0;
  }
  public addOneCounter(this: any, when: any) {
    when(/^I add (.*) to counter$/, (value: string) => {
      const valueToAdd = parseInt(value, 0);
      console.log('adding to counter ', valueToAdd);
      this.counter += valueToAdd;
    });
  }
  public counterShouldEqual(this: any, then: any) {
    then(/^the counter should equal (.*)$/, (expected: string) => {
      expect(this.counter).toEqual(parseInt(expected, 0));
    });
  }
}
```
That works now 👍 I will try in our real app and close the issue if it's all good

**Comment by Maxim-Filimonov** [comment]
It works, with our internal examples 👍 Thanks for your help @bencompton
