### ISSUE TITLE
skip scenarios based on tagging

### ISSUE THREAD

**Issue by SONIKASUHANI** [bencompton/jest-cucumber#48]
Is is necessary to implement scenarios in steps if you want to skip it using tagging.?  The use case is : if a feature contains a scenario which is just a place holder or tagged as manual (for record keeping) , we want to skip it. Noticed a error saying, it has to be implemented in steps whereas in Java Cucumber it is not the case, skip scenarios are not checked in step definition , it simply ignores from feature file.

Help is really appreciated here .
@bencompton  Appreciate your support here

**Comment by bencompton** [comment]
Looks like there was a bug. Should be fixed now in v2.0.5.
