### ISSUE TITLE
Tagging is not working

### ISSUE THREAD

**Issue by martotkd1** [bencompton/jest-cucumber#55]
Tagging stopped working from 2.0.5 version.

**Comment by bencompton** [comment]
Thanks for the heads up! I discovered and fixed a couple of issues with tag filtering, and now it appears to be working perfectly in my project. Sorry for the issues. Try version 2.0.10 and let me know how it works for you.

**Comment by martotkd1** [comment]
Hello @bencompton ,

Tagging works if i use @exclude but @ignore is still not working.

**Comment by bencompton** [comment]
The issue has to do with and / or / not being in the tag. You reported this issue last month, and I fixed it, but it seems I published to NPM and never pushed up the commit. Everything should be good to go now in version 2.0.11.

I'll have to work on tightening up the deployment process to ensure this doesn't happen again.

**Comment by martotkd1** [comment]
I checked and it works fine in 2.0.11.
Thanks!

**Comment by bencompton** [comment]
Great, thanks for checking!

**Comment by jasonellington** [comment]
@bencompton are we not allowed to use custom tags? Additionally, I tried following your additional configuration documentation and was unable to get tagFilters working properly, do they work with Scenario Outlines?
