### ISSUE TITLE
Error parsing feature Gherkin: Gherkin.Parser is not a constructor

### ISSUE THREAD

**Issue by spirosikmd** [bencompton/jest-cucumber#56]
Hi there! Thank you for this great package!

Using the version `1.0.15` of `jest-cucumber` I get the following error:

```
Error parsing feature Gherkin: Gherkin.Parser is not a constructor
```

You can check my setup in this repository spirosikmd/jest-cucumber-puppeteer-example#5

Is there something wrong with my configuration?

**Comment by bencompton** [comment]
The latest version (2.0.11) appears to work. Are you able to use that instead?

**Comment by spirosikmd** [comment]
Version `2.0.11` works! Thank you 🎉
