### ISSUE TITLE
Auto generate is not working

### ISSUE THREAD

**Issue by dev-nicelee** [bencompton/jest-cucumber#58]
Auto generating of steps is not working like [example gif](https://github.com/bencompton/jest-cucumber/blob/master/images/jest-cucumber-demo.gif).

It could be a problem of my configuration of jest-cucumber. But, could you help me how to enable it?🤔

**Comment by pedrowilkens** [comment]
Hi, could you be explicit in your explanation and could you show your configuration?  So that we can help you.

**Comment by pedrowilkens** [comment]
Hi, @dev-nicelee do you mean autogenerating steps without writing everything repeatedly? There is an issue labeled "Need I really to define each Scenario with its dependent steps outside of the feature file?" 
Do you mean that?  I would love to help you :)

**Comment by pedrowilkens** [comment]
Ok, sorry @dev-nicelee my fault I should have been looking at the picture. I am not the maintainer of jest-cucumber but as far as I know the steps will be auto-generated on jest execution if the scenario isn't defined in javascript. So you can copy and paste the scaffold from your Terminal.

**Comment by dev-nicelee** [comment]
@pedrowilkens Yes, I've already executed like you did.. But I hope there's other way like the attached picture above🤔 Btw, thanks for your comment 👍

**Comment by PeterPorzuczek** [comment]
Hi,

I created a plugin for VSC that allows code generation based on this library.

[Install from marketplace](https://marketplace.visualstudio.com/items?itemName=Piotr-Porzuczek.jest-cucumber-code-generator-extension)

[Contribute to extension](https://github.com/PeterPorzuczek/jest-cucumber-code-generator-extension)

I think it some solution and we can close this issue.

**Comment by dev-nicelee** [comment]
@PeterPorzuczek I appreciate your work and kudos! I haven’t tested it all but will work for this issue. Thanks you all and I’m closing this issue!
