### ISSUE TITLE
Feature: sub steps

### ISSUE THREAD

**Issue by fider** [bencompton/jest-cucumber#66]
**Feature description:**
Possibility to define substeps, eg:

**How it is currently:**
```js
// stepDefinition.ts
Then(/"(.*?)" register step 1/, ... );
Then(/"(.*?)" register step 2/, ... );
Then(/"(.*?)" register step 3/, ... );
// If I would like to group them I have to create new step and copy/paste implementation.
```
```js
// A.feature
Then "device_1" register step 1
Then "device_1" register step 2
Then "device_1" register step 3
```
```js
// B.feature
Then "device_2" register step 1
Then "device_2" register step 2
Then "device_2" register step 3
```

**How it may looks like:** 
```js
// stepDefinition.ts
const registerStep1 = Then(/"(.*?)" register step 1/, ... );
const registerStep2 = Then(/"(.*?)" register step 1/, ... );
const registerStep3 = Then(/"(.*?)" register step 1/, ... );
Then(/"(.*?)" complete register/, async (deviceName) => {
  return [registerStep1(deviceName) , registerStep2(deviceName) , registerStep3(deviceName) ]
});
```
```js
// A.feature
Then "device_1" complete register
```
```js
// B.feature
Then "device_2" complete register
```
We can also resue substeps in feature files
```js
// C.feature
Then "device_3" register step 3
// ...
Then "device_3" register step 1
```

**Example html report:**
Each step that contains substeps can contain folding/unfolding button (just like featrue and scenario).
![image](https://user-images.githubusercontent.com/1457742/65326406-aaa2c880-dbb1-11e9-8ab0-5d1dcf6314b3.png)

**Why this feature is important:**
- Wrapping cucumber steps into other steps allows me to keep granulation in test steps, reuse code and save a lot of time (eg. let's assume that I just added new steps to "complete register" sequence - I have to update it only in one place instead of 2 or even 50).
- Without this functionality writing code using cucumber is like programming in language that do not allows you to nest functions calls.
- I am aware of fact that I can wrap code of "step 1", "2" and "3" into "register complete" but then I will not be able to use each step as standalone fragment of code. Putting whole code into single step limits functionality and make reports less clear.

**Comment by bencompton** [comment]
You may have already considered scenario outlines, but it seems that scenario outlines could get you a lot of the re-use you're looking to accomplish:

```
Scenario Outline: Registering Devices
....
Then "<DeviceName>" register step <StepNumber>
...

Examples:

| DeviceName | StepNumber |
| device_1   | 1          |
| device_2   | 2          |
```

Generally, this library is intended to bring idiomatic Cucumber to Jest, and leverages the official Cucumber feature file parser. This is delving into territory that, while may be useful to some people, is a pretty major departure from idiomatic Cucumber, and would require custom feature file parsing.

**Comment by bencompton** [comment]
Closing due to staleness. Feel free to create a new issue if there is more to discuss.
