### ISSUE TITLE
Scenario Outlines and Docstrings

### ISSUE THREAD

**Issue by bencompton** [bencompton/jest-cucumber#7]
When a step in a scenario outline has a docstring referencing a column from the example table, it should be replaced with the value from the example table. For example:

```gherkin
Scenario Outline: Example table values in Docstrings
  Given an example table value is referenced in a docstring
  """
  <Data1> is cool
  """

  ...

Examples:
  | Data 1 |
  | value 1|
  | value 2|
```

In the above example, `<Data1>` in the Docstring should be replaced with "value 1" for the first example, and "value 2" for the second example.

**Comment by SirSkorpan** [comment]
@bencompton I'm preparing a PR to add this functionality, solving (hopefully) this issue as well as #79. If it matters to you, do you prefer to have all changes in one (feature) commit or multiple (about 4-5 smaller) commits?

**Comment by SirSkorpan** [comment]
@bencompton I guess this issue could be closed now?

**Comment by bencompton** [comment]
This is now in 3.0.0, which is considered latest and no longer preview.
