### ISSUE TITLE
How can i get cucumber scenario variables in title?

### ISSUE THREAD

**Issue by Tuely** [bencompton/jest-cucumber#70]
How can i get cucumber scenario variables in title?

I am having issue with my scenario name. I am expecting this should generate scenario name as "Residency as under 1 year" ..... But actual it's generating as
"ResidencyasUKResidiency("Under 1 year","Supplied")"

Can some one please help me to solve this

Scenario Outline: Residency as
Given I have built a policy with the following details
Then I verify UK Residence Parameter ''

Examples:
| UkResidency | UkResidence |
| Under 1 Year | Supplied |

**Comment by bencompton** [comment]
This doesn't appear to be an issue any longer as of #68
