### ISSUE TITLE
jest not identifying the wrong step declarations

### ISSUE THREAD

**Issue by phani17c** [bencompton/jest-cucumber#71]
**To Reproduce**
Feature file (written in cucumber):
Scenario: I am scenario
Given I am given step
When I am when step
Then I am then step

step definitions:
test('I am a scenario', ({given,when,then})=>{

given('I am given step', ()=>{});

when('I am when step',()=>{});

then('Then I am then step', ()=>{}); //this is a wrong declaration of step definition
});

The main issue is jest is not identifying the issue and skipping these type of tests and not running at all in a test suit.

**Expected behavior**
Jest should throw an exception saying that step declaration it wrong.

Is this happening because of jest considering Then before step definitions is not an error?

**envinfo**
"jest": "^24.9.0",
"jest-cucumber": "^1.0.9",

System:
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Binaries:
Node: 10.14.0
npm: 6.9.0

**Comment by bencompton** [comment]
When I attempt to reproduce in the current master branch, as well as the master branch as of 2.0.11, I get the output below. I suspect that this was an old issue in 1.0.9 that has since been fixed.

```
    No scenarios found in feature file that match scenario title "I am a scenario."

    Feature file has a scenario titled "I am scenario", but no match found in step definitions. Try adding the following code:

    test('I am scenario', ({ given, when, then }) => {
        given('I am given step', () => {

        });

        when('I am when step', () => {

        });

        then('I am then step', () => {

        });
    });
```
