### ISSUE TITLE
Update jest to v23.x

### ISSUE THREAD

**Issue by npasquet** [bencompton/jest-cucumber#8]
Hello,

Jest@v23.x introduce a new parameter `propertyMatchers` for `expect.toMatchSnapshot()` which is useful when snapshotting generated fields like Date, IDS...

It would be great to bump jest version in this package.

**Comment by bencompton** [comment]
Agreed, keeping this library on the latest version of Jest would be great. I will be adding the greenkeeper bot to ensure that this library is continually kept up to date.

**Comment by bencompton** [comment]
Available in v1.0.7
