### ISSUE TITLE
What VS code plugins did you use for your gif readme demo?

### ISSUE THREAD

**Issue by lolpez** [bencompton/jest-cucumber#82]
Not an actual issue but I am curious what plugins you used for your [gif demo](https://github.com/bencompton/jest-cucumber/raw/master/images/jest-cucumber-demo.gif?raw=true) in your readme file.
I find them useful :)

**Comment by bencompton** [comment]
It has been a couple of years, and I unfortunately don't recall what I ended up using. I do remember that it took a long time to find something that worked and wasn't behind a paywall.
