### ISSUE TITLE
Step definition returning undefined

### ISSUE THREAD

**Issue by eprislac** [bencompton/jest-cucumber#89]
Am working with jest, jest-cucumber and react, and am experiencing a weird issue with my step declarations.

I have gherkin defined as so:
```gherkin
Scenario: Selecting a theme
    Given A ThemeMenu component with one active and two inactive themes
    When I click on 'Theme B'
    Then 'Theme B' should be selected
    And 'Theme A' should be deselected
```
and my step definition defined as so:
```js
...
then(`'Theme A' should be deselected`, () => {
  const foundTheme =  component
     .find(`#activateThemeButtonGroup-1`)
     .first()

  expect(foundTheme.hasClass('active')).toBeFalsy()
})
```

however, when I run jest, I get this error:
```
not ok 8 ● ThemeMenu › encountered a declaration exception
#
Expected step #4 in scenario "Selecting a theme" to match "'Theme A' should be deselected"s) defined.
```

where is that extra `s)` coming from, and how do I make it stop?

**Comment by mkoelle** [comment]
I may have a similar issue, or it may take place in the same section of code.

It looks like the errors we are getting are a mashup of the text from line 43 and 55 of `src/validation/step-definition-validation.ts`

``` js
# Line 47
errors.push(`Scenario "${parsedScenario.title}" has ${parsedStepCount} step(s) in the feature file, but ${stepDefinitionCount} step definition(s) defined.`);

# Line 55
errors.push(`Expected step #${index + 1} in scenario "${parsedScenario.title}" to match "${parsedStep.stepText}"`);
```

With a sample scenario of

``` gherkin
Scenario: Getting to know your marbles
    Given I have a lovely jar of mixed marbles
    When I sort my marbles
    Then some of the marbles will be blue
    And some of the marbles will be red
```

And the shared step definition
``` js
...
then(/^some of the marbles will be (.*)$/, (color) => {
      const filteredMarbles = marbles.filter( (m) => m.color == color );
      expect(filteredMarbles.length).toBeGreaterThan(0);
});
```

As long as I have both statements about the red and blue marbles I get the error:

``` err
encountered a declaration exception (7ms)
Counting Marbles › encountered a declaration exception
Expected step #4 in scenario "Getting to know your marbles" to match "some of the marbles will be red"fined.

...

      at Object.<anonymous>.exports.ensureFeatureFileAndStepDefinitionScenarioHaveSameSteps (node_modules/jest-cucumber/src/validation/step-definition-validation.ts:60:15)
      at tests/marbleJar.spec.ts:7:3
      at Object.<anonymous> (tests/marbleJar.spec.ts:5:1)
```

I set up a sample repository to demonstrate the behavior, [github.com/mkoelle-shelved/jest-cucumber-marbles](https://github.com/mkoelle-shelved/jest-cucumber-marbles)
The test is in the passing state, and uncommenting the last condition will cause it to fail.

My dependencies are:
    "jest-cucumber": "^2.0.11",
    "ts-jest": "^26.1.0",
    "typescript": "^3.9.5"

**Comment by bencompton** [comment]
Jest Cucumber works a bit differently from Cucumber in that it expects a every step in your feature file to have a matching step definition declared. In cases where the same step definition can match multiple steps, that step definition can be reused by extracting it into a function:

```javascript
const thenSomeOfTheMarblesWillBeX = (then: DefineStepFunction) => {
    then(/^some of the marbles will be (.*)$/, (color) => {
        ...
    });
};

defineFeature(feature, (test) => {
    test('Getting to know your marbles', ({ given, when, then }) => {
        ...
        thenSomeOfTheMarblesWillBeX(then);
        thenSomeOfTheMarblesWillBeX(then);
    });
});
```

As for the extra characters in the error messages, the step validation errors were getting separated with carriage returns instead of newline characters, and that was causing the messages to get layered on top of each other in certain terminals. This is now fixed on master and will be released before the end of this week.
