### ISSUE TITLE
describe, it

### ISSUE THREAD

**Issue by oarashi** [bencompton/jest-cucumber#9]
Is it possible to use `describe` and `it` from jest? 
Thank you!

**Comment by bencompton** [comment]
Maybe you could elaborate more on what you're looking to accomplish?

The goal of jest-cucumber is to allow Gherkin integration tests to run on top of Jest, with Cucumber syntax as an alternative to `describe` and `it` blocks. If you have other unit and integration tests that you want to run in Jest along with your Gherkin tests, then using `describe` and `it` blocks for those is perfectly fine. You likely would want to put those tests in separate files, but there shouldn't be anything preventing you from also putting them inside of your step definition files (outside of the defineFeature block).

Something like this will technically also work (when running `npm test`, not with the VS Code plug-in), although YMMV:

```javascript
defineFeature(feature, describe => {
    describe('Launching a SpaceX rocket', ({ defineStep  }) => {
        const it = defineStep;
        let rocket: Rocket;
    
        it('I am Elon Musk attempting to launch a rocket into space', () => {
            rocket = new Rocket();
        });

        it('I launch the rocket', () => {
            rocket.launch();
        });

        it('the rocket should end up in space', () => {
            expect(rocket.isInSpace).toBe(true);
        });        

        it('the booster(s) should land back on the launch pad', () => {
            expect(rocket.boostersLanded).toBe(true);
        });

        it('nobody should doubt me ever again', () => {
            expect('people').not.toBe('');
        });
    });
});
```
