### ISSUE TITLE
How to have multiple scenarios match - given, when, then - when you have to specify the scenario within the test?

### ISSUE THREAD

**Issue by inspiraller** [bencompton/jest-cucumber#95]
Hi

I have a working example here:
**example-myvar.feature**
```cucumber
Feature: example-myvar
 
Scenario: Example use case 1
    Given myvar === 2
    When myvar is incremented
    Then myvar should = 3
```

**steps/specific-feature.step.js**
```javascript
import { defineFeature, loadFeature } from 'jest-cucumber';

// const feature = loadFeature(path.join(__dirname, '../features/example-myvar.feature');
const feature = loadFeature('../features/example-myvar.feature', { loadRelativePath: true });

defineFeature(feature, test => {
  let myvar = 0;
  beforeEach(() => {
    myvar = 0;
  });

  test('Example use case 1', ({ given, when, then }) => {
    given('myvar === 2', () => {
      myvar = 2;
    });
    when('myvar is incremented', () => {
      myvar += 1;
    });
    then('myvar should = 3', () => {
      expect(myvar).toBe(3);
    });
  });
});
```

That seems to imply you must always speciify the 'scenario' name to be associated with the individual test - ie : 'Example use case 1'. My feature which has scenario: 'Example use case 1' then will be operated by this test.

However this is not full cucumber functionality. The main use case is the other way around, that the feature does not know about any specific test and in fact just matches with the step given, when, then regex. 

I tried to follow the examples from these folders with your - autobind example, so that I didn't have to specify a particular test and therefore targeted scenario:
https://github.com/bencompton/jest-cucumber/blob/02b30c4cd52142a75af3eba8d6e911b80bf285f8/examples/ecmascript/specs/step-definitions/auto-step-binding.steps.js

I created this file:

**steps/generic-feature.step.js**
```javascript
import { loadFeatures, autoBindSteps } from 'jest-cucumber';

const generic = ({ given, when, then }) => {
  let myvar;
  beforeEach(() => {
    myvar = 0;
  });
  given('myvar === 2', () => {
    myvar = 2;
  });
  when('myvar is incremented', () => {
    myvar += 1;
  });
  then('myvar should = 3', () => {
    expect(myvar).toBe(3);
  });
};

const hack = {};
export { generic, hack };

const features = loadFeatures('../features/*.feature', { loadRelativePath: true });

autoBindSteps(features, [generic]);
```

Firstly eslint complains about:
- Missing return type on function.
- Object pattern argument should be typed.

Secondly and most importantly I get this error:
> Test suite failed to run

   Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
      at testRunner.on (node_modules/@jest/core/build/TestScheduler.js:304:17)
      at Promise.all.staticListeners.map (node_modules/emittery/index.js:260:13)
          at Array.map (<anonymous>)
      at Emittery.Typed.emit (node_modules/emittery/index.js:258:23)

I'm curious how its possible to have multiple features without the test locked to each scenario. 
I want to have 100+ scenarios that will always be matched by the steps. Certainly not the other way around - 100 steps because I have 100 scenarios.

Can you advise how to do this if possible via a demo or example?
thanks

**Comment by inspiraller** [comment]
I've got around it by this method, though it seems a bit hacky, I'm, sure there is a better approach

```javascript
import { defineFeature, loadFeature } from 'jest-cucumber';
import fs from 'fs';
import path from 'path';

const folder = path.join(__dirname, '../features');
const features = fs.readdirSync(folder);

let props;

const myvarTest = ({ given, when, then }) => {
  given(/(\w+) \=\=\= ([0-9])/, ($1, $2) => {
    props[$1] = Number($2);
  });
  when(/(\w+) is incremented/, $1 => {
    props[$1] += 1;
  });
  then(/(\w+) should = ([0-9])/, ($1, $2) => {
    expect(props[$1]).toBe(Number($2));
  });
};

features.forEach(file => {
  const feature = loadFeature(`../features/${file}`, { loadRelativePath: true });
  defineFeature(feature, test => {
    beforeEach(() => {
      props = {
        myvar: 0
      };
    });
    feature.scenarios.forEach(item => {
      test(item.title, opt => {
        myvarTest(opt);
      });
    });
  });
});
```

Advise if this is something you are looking to change and implement as a config or something otherwise feel free to close this.

**Comment by bencompton** [comment]
The `autoBindSteps` functionality essentially does the same type of loop as the workaround above. If you were getting "your test suite must contain at least one test" when you did in fact have steps defined, then perhaps the `testMatch` settings weren't quite correct. I'd suggest giving `autoBindSteps` another try if you haven't already, though it's possible you discovered some sort of an issue with it that perhaps is particular to your setup.

**Comment by mentierd** [comment]
@inspiraller instead of trying to understand what autoBindSteps is actually doing, you should check out [cucumber-jest](https://github.com/mentierd/cucumber-jest)

**Comment by robert-skarzycki** [comment]
@inspiraller, please check if you configured `autoBindSteps` correctly, as @bencompton suggested. I was facing similar problems, but finally it turned out that I had passed incorrect path to `loadFeatures` (just had copied path from example and forgot to adjust to my project folders structure :P).

P.S. @mainfraame, not sure what is the point in suggesting people to migrate to your library in this place (apparently you are a contributor of `cucumber-jest`) - IMHO it would be fair to uncover that fact when suggesting such a thing here. Especially when you are not pointing what problem your library solves that `jest-cucumber` doesn't (`jest-cucumber` apparently allows pure Jest-style and auto-binding of steps, as opposed your library offers only the latter). Personally, I didn't realize in the beginning you are marketing your library here, so I've tried that, but after facing some problems with Cucumber version, lack of typescript support, finally get back here and I am happy with `autoBindSteps`.

**Comment by kevincmanning** [comment]
@robert-skarzycki I agree it should have been disclosed that he was marketing his own project, but tbh this project has a cucumber anti-pattern in the examples and seems to be very cumbersome to work with. (although it does seem to have a more active user base and thus more community support)

I ended up going with @mainfraame 's project after struggling with this one to get it to work how I expected it to given my previous usage of Cucumber with Java
