### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by MdImthiyas** [bencompton/jest-cucumber#97]
Hi,

I try to migrate my jest tests cases with cucumber integration.
So I define my first scenario and its associated step_definitions, then when I run it, I got:

![image](https://user-images.githubusercontent.com/48554860/94041268-a3775180-fde7-11ea-9a8b-d405225ca15e.png)

**Please find the Steps File.**

const {
    defineFeature,
    loadFeature
} = require('jest-cucumber');

const feature = loadFeature(
  './src/test/features/1.1_User_Location_Homepage_Landing.feature'
);

defineFeature(feature, (test) => {                      // <<----- **Failed here**
  let isEnabledGeoLocation = false;
  let zipcodeValue = undefined;
  let inventoriesObj = [];

  test('Check whether the system is able to fetch the users geolocation automatically and able to list cars within the zipcode radius.', ({
    given,
    when,
    then,
    and,
  }) => {
    given('User lands on the NCI page', () => {});

    when('Geolocation is enable', () => {
      isEnabledGeoLocation = true;
      zipcodeValue = '07097';
    });

    then('Zipcode field should be populated with geolocated value', () => {
      if (isEnabledGeoLocation) {
        expect(zipcodeValue).toBeTruthy();
        inventoriesObj = [
          {
            model: 'XC90',
            trim: 'MOMENTUM',
            driveTrain: 'AWD',
          },
        ];
      }
    });

    and('Number of cars count should be displayed as Vehicles Matching', () => {
      if (isEnabledGeoLocation) {
        expect(inventoriesObj.length).toBeGreaterThanOrEqual(0);
      }
    });

    and('Cars should be listed', () => {
      if (isEnabledGeoLocation && inventoriesObj.length > 0) {
        expect(inventoriesObj).toBeDefined();
      }
    });
  });
});

**Used below Package Version:**

"jest": "^26.0.1",
 "cucumber": "^6.0.5",
 "@types/cucumber": "^6.0.1",
 "jest-cucumber": "^3.0.0",

**I've added below code in jest.config.js file.**

"testMatch": [
    "<rootDir>/src/test/**/*.steps.js"
],

Node Version: v11.15.0

Kindly help me to resolve this issue.

**Comment by bencompton** [comment]
From the screenshot above, it appears Cucumber was being used as the test runner, whereas this package is designed to build and run Gherkin scenarios using Jest as the test runner. Closing, since this doesn't appear to be an issue with this package, but feel free to re-open if I misunderstood.
